showGrid: false

url:               http://cel76.com
title:             cel76
author:            cel76
email:             cel76@cel76.com
description:       queuing in line since 1976
baseurl:           ""
google_tracking_id: "UA-73820115-1"
#image:             "/img/bg-01.jpg"

# Set header image count to the number of bg-NN.jpg images.
# This will randomly select a header image when none is specified.
headerImageCount: 7

# Social Profiles
twitter_username:  cel76
github_username:   cel76

# Build settings
#markdown:          kramdown
#paginate_path:     "/posts/page:num/"
#plugins:
#  - jekyll-feed
#  - jekyll-paginate

root: /

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
related_posts_count: 10 # Number of related articles to display.

# Category plugin (https://github.com/recurser/jekyll-plugins)
category_dir: category

tag_dir: tag

exclude: [vendor, Rakefile, readme.md, bitrise.yml, Gemfile, Gemfile.lock]
include: [.nojekyll]

plugins: [jekyll-paginate]